version: "3.9"
services:
  traefik:
    container_name: "traefik"
    image: "traefik:v2.6"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/cert:/etc/cert"
      - "./docker/traefik/config.yml:/etc/traefik/traefik.yml"
      - "./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${HOST_NAME}`)"
      - "traefik.http.routers.${ROUTER_NAME}.service=api@internal"
      - "traefik.http.routers.${ROUTER_NAME}.tls=true"
networks:
  default:
    name: "proxy"
    external: true